services:
  app:
    build:
      context: .
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --no-input &&
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
    env_file:
      - .env

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
  
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "1234:1243"

  nginx:
    image: nginx:latest
    volumes:  
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

volumes:
  static_volume:
