services:
  app:
    build:
      context: .
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --no-input &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --log-level info"
    volumes:
      - static_volume:/app/static
    env_file:
      - .env

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    
  nginx:
    image: nginx:latest
    volumes:  
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"

volumes:
  static_volume: